config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  resources :categories
  resources :varieties

  get 'find_books/:category', to: 'bookmarks#find_books', as: 'find_books'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :variety
  belongs_to :category


end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :parent, class_name: 'Category', optional: true, foreign_key: :category_id
    has_many :children, class_name: 'Category', dependent: :destroy
    has_many :bookmarks
end

app/models/variety.rb
class Variety < ApplicationRecord
    has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[ show edit update destroy ]

  # GET /bookmarks or /bookmarks.json
  def index
    @bookmarks = Bookmark.all
    @bookmark = Bookmark.new

    @pie_chart_variety = Bookmark.joins(:variety).group('varieties.name').order(value: :desc).count

  end

  # GET /bookmarks/1 or /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks or /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        @bookmarks = Bookmark.all
        format.html { redirect_to @bookmark, notice: "Bookmark was successfully created." }
        format.json { render :show, status: :created, location: @bookmark }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1 or /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: "Bookmark was successfully updated." }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1 or /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: "Bookmark was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def find_books
    category = Category.where(name: params[:category]).first
    
    json = {'bookmarks' => {category.name.to_s => []}}

    # marcadores de primer nivel
    json['bookmarks'][category.name.to_s.to_s].push({"bookmarks": category.bookmarks.pluck(:name)})

    # marcadores de segundo nivel
    category.children.each do |child|
      json['bookmarks'][category.name.to_s.to_s].push({"subsection": child.name, "bookmarks": child.bookmarks.pluck(:name)})
    end

    # TODO: marcadores en n niveles

    render json: json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bookmark_params
      params.require(:bookmark).permit(:name, :url, :variety_id, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :public)
    end
end

app/controllers/varieties_controller.rb
class VarietiesController < ApplicationController
  before_action :set_variety, only: %i[ show edit update destroy ]

  # GET /varieties or /varieties.json
  def index
    @varieties = Variety.all
  end

  # GET /varieties/1 or /varieties/1.json
  def show
  end

  # GET /varieties/new
  def new
    @variety = Variety.new
  end

  # GET /varieties/1/edit
  def edit
  end

  # POST /varieties or /varieties.json
  def create
    @variety = Variety.new(variety_params)

    respond_to do |format|
      if @variety.save
        format.html { redirect_to @variety, notice: "Variety was successfully created." }
        format.json { render :show, status: :created, location: @variety }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @variety.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /varieties/1 or /varieties/1.json
  def update
    respond_to do |format|
      if @variety.update(variety_params)
        format.html { redirect_to @variety, notice: "Variety was successfully updated." }
        format.json { render :show, status: :ok, location: @variety }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @variety.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /varieties/1 or /varieties/1.json
  def destroy
    @variety.destroy
    respond_to do |format|
      format.html { redirect_to varieties_url, notice: "Variety was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variety
      @variety = Variety.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def variety_params
      params.require(:variety).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/varieties_helper.rb
module VarietiesHelper
end

app/views/bookmarks/_bookmark.html.erb
<tr>
    <td><%= bookmark.name %></td>
    <td><%= bookmark.url %></td>
    <td><%= bookmark.variety.name %></td>
    <td><%= bookmark.category.name %></td>
    <td><%= link_to 'Show', bookmark %></td>
    <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
    <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/bookmarks/_form.html.erb
<%= form_with(model: bookmark, remote: true, data: { confirm: 'Are you sure?' }) do |form| %>
  <% if bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :variety_id %>
    <%= form.select :variety_id, Variety.all.collect {|c| [ c.name, c.id ] }, id: :bookmark_variety_id, include_blank: false %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, Category.all.collect {|c| [ c.name, c.id ] }, id: :bookmark_category_id, include_blank: false %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookmarks/create.js.erb
$('tbody').html('<%= j render @bookmarks %>')

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookmarks</h1>

<%= render 'form', bookmark: @bookmark %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Variety</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @bookmarks %>
  </tbody>
</table>

<div>
  <%= pie_chart @pie_chart_variety, donut: true, title: "Variety count" %>
</div>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bookmark.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<p>
  <strong>Variety:</strong>
  <%= @bookmark.variety %>
</p>

<p>
  <strong>Category:</strong>
  <%= @bookmark.category %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :public %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Public</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.public %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Public:</strong>
  <%= @category.public %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/varieties/_form.html.erb
<%= form_with(model: variety, local: true) do |form| %>
  <% if variety.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(variety.errors.count, "error") %> prohibited this variety from being saved:</h2>

      <ul>
      <% variety.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/varieties/edit.html.erb
<h1>Editing Variety</h1>

<%= render 'form', variety: @variety %>

<%= link_to 'Show', @variety %> |
<%= link_to 'Back', varieties_path %>

app/views/varieties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Varieties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @varieties.each do |variety| %>
      <tr>
        <td><%= variety.name %></td>
        <td><%= link_to 'Show', variety %></td>
        <td><%= link_to 'Edit', edit_variety_path(variety) %></td>
        <td><%= link_to 'Destroy', variety, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variety', new_variety_path %>

app/views/varieties/new.html.erb
<h1>New Variety</h1>

<%= render 'form', variety: @variety %>

<%= link_to 'Back', varieties_path %>

app/views/varieties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @variety.name %>
</p>

<%= link_to 'Edit', edit_variety_path(@variety) %> |
<%= link_to 'Back', varieties_path %>